WIDTH, HEIGHT = 800, 800
TILE_SIZE = 32

all_level = [
    [
        "B                                                                                    G",
        "B                                                                                    G",
        "B                                                                                    G",
        "B                                                                                    G",
        "B                                                                                    G",
        "B                                                                                    G",
        "B                                                                                    G",
        "B                                                                                    G",
        "B                                                  DDDDDDD                           G",
        "B                                                  DDDDDD                            G",
        "B                                                  DDDDDD                            G",
        "B                                                  DDDDDD                            G",
        "B                                                  DDDDD                             G",
        "B                                                  DDDDD                             G",
        "B                                                  DDDDD            DDDDD            G",
        "B                                                DDDDD                               G",
        "B                         DDDD                   DDDD                                G",
        "B                 DDDDD                          DDDD C                              G",
        "B                                 DDDDD          DDDD              DDD               G",
        "B                                                DDDD              DDD               G",
        "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",
        "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",
        "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",    
        "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",
        "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",            
        "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",            
        "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",             
    ],
    [ 
        "B                         G",
        "B                         G",
        "B                         G",
        "B C                       G",
        "B                         G",
        "B                    DDDDDD",
        "B                        DD",
        "B    DDD                 DD",
        "B    DDD                 DD",
        "D^^^^DDD                 DD",
        "DDDDDDD                  DD",
        "DDDDD            DD      DD",
        "DDDD             DD      DD",
        "DD                       DD",
        "DD                       DD",
        "B                      DDDD",
        "B                      DDDD",
        "D                      DDDD",
        "B                    DDDDDD",
        "B                        DD",
        "B                        DD",
        "DDDDDD    DDDDD          DD",
        "DDDDDD    DDDDD    ^^^^^^DD",
        "DDDDDD^^^^DDDDD^^^^DDDDDDDD",    
        "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    ],
    [ 
        "B                   DGGGGDD",
        "B                   D    DD",
        "B                   D    DD",
        "B                   D    DD",
        "B                   D    DD",
        "B                   D    DD",
        "B                   D    DD",
        "B      DDDDDD            DD",
        "B      ^^^^^^            DD",
        "B                        DD",
        "B         C   DD      DDDDD",
        "BDD                      DD",
        "B      ^^^^^^^^^^        DD",
        "B      DDDDDDDDDD        DD",
        "B    DDDDDDDDDDDD^^^     DD",
        "B      DDDDDDDDDDDDD^^^^^DD",
        "B      DDDDDDDDDDDDDDDDDDDD",
        "B      DDDDDDDDDDDDDDDDDDDD",
        "BDD    DDDDDDDDDDDDDDDDDDDD",
        "B      DDDDDDDDDDDDDDDDDDDD",
        "B      DDDDDDDDDDDDDDDDDDDD",
        "B      DDDDDDDDDDDDDDDDDDDD",
        "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "DDDDDDDDDDDDDDDDDDDDDDDDDDD",    
        "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    ]
]