from level import Level

WIDTH, HEIGHT = 800, 800
TILE_SIZE = 32

level_1_grid = [
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                  DDDDDDD                           G",
    "B                                                  DDDDDD                            G",
    "B                                                  DDDDDD                            G",
    "B                                                  DDDDDD                            G",
    "B                                                  DDDDD                             G",
    "B                                                  DDDDD                             G",
    "B                                                  DDDDD            DDDDD            G",
    "B                                                DDDDD                               G",
    "B                         DDDD                   DDDD                                G",
    "B                 DDDDD                          DDDD C                              G",
    "B                                 DDDDD          DDDD              DDD               G",
    "B                                                DDDD              DDD               G",
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",    
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",            
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",            
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",             
]
level_2_grid = [ 
    "B                         G",
    "B                         G",
    "B                         G",
    "B C                       G",
    "B                         G",
    "B                    DDDDDD",
    "B                        DD",
    "B    DDD                 DD",
    "B    DDD                 DD",
    "D^^^^DDD                 DD",
    "DDDDDDD                  DD",
    "DDDDD            DD      DD",
    "DDDD             DD      DD",
    "DD                       DD",
    "DD                       DD",
    "L                      DDDD",
    "L                      DDDD",
    "L                      DDDD",
    "L                    DDDDDD",
    "L                        DD",
    "L                        DD",
    "DDDDDD    DDDDD          DD",
    "DDDDDD    DDDDD    ^^^^^^DD",
    "DDDDDD^^^^DDDDD^^^^DDDDDDDD",    
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
]
level_3_grid = [ 
    "B                   DGGGGDD",
    "B                   D    DD",
    "B                   D    DD",
    "B                   D    DD",
    "B                   D    DD",
    "B                   D    DD",
    "B                   D    DD",
    "B      DDDDDD            DD",
    "B      ^^^^^^            DD",
    "B                        DD",
    "B         C   DD      DDDDD",
    "DDD                      DD",
    "B      ^^^^^^^^^^        DD",
    "B      DDDDDDDDDD        DD",
    "B    DDDDDDDDDDDD^^^     DD",
    "B      DDDDDDDDDDDDD^^^^^DD",
    "B      DDDDDDDDDDDDDDDDDDDD",
    "B      DDDDDDDDDDDDDDDDDDDD",
    "DDD    DDDDDDDDDDDDDDDDDDDD",
    "L      DDDDDDDDDDDDDDDDDDDD",
    "L      DDDDDDDDDDDDDDDDDDDD",
    "L      DDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",    
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
]
level_4_grid = [ 
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDD                   DD",
    "DDDD                 C   DD",
    "DD                       DD",
    "G                    ^   DD",
    "G                   ^D^  DD",
    "G                   ^D^  DD",
    "G                   ^D^  DD",
    "DDDDDD               ^   DD",
    "B                        DD",
    "B                        DD",
    "B                 DDDDDDDDD",
    "B                       DDD",
    "B                        DD",
    "DDDDDDDD                 DD",
    "DDDD                     DD",
    "DDD               DD     DD",
    "DD                DDDDD  DD",
    "L                        DD",
    "L                        DD",
    "L                      DDDD",
    "L                    DDDDDD",
    "DDDDDD            DDDDDDDDD",
    "DDDDDD^^^^^^^^^^^^DDDDDDDDD",    
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
]

level_5_grid = [ 
    "DDDDDD                  ^DD",
    "DDDDDD                  ^DD",
    "DDDD                    ^DD",
    "DD                      ^DD",
    "D                        DD",
    "D            ^^^^        DD",
    "DDDDDD^   ^DDDDDDDDDD    DD",
    "DDDDDD^   ^DDDDDDDDDD^   DD",
    "DDDDDD^   ^DDDDDDDDDD^   DD",
    "DDDDDD^   ^DDDDDDDDDD^   DD",
    "DDDDDD^   ^DDDDDDDDDD^   DD",
    "DD        ^DDDDDDDDDD    DD",
    "B  C           DDDDDD    DD",
    "B    ^         DDDDDD   ^DD",
    "DD   D^        DDDDDD   ^DD",
    "D^   D^^^^^    DDDDDD    DD",
    "D^    DDDDD    DDDDDD    DD",
    "D^      ^^^       DDD^   DD",
    "D^^^               DD^   DD",
    "DDDDDDDDDDDDDDD    DD     L",
    "G                  DD     L",
    "G                  DD     L",
    "G                 DDDDDDDDD",
    "DDDDDDD       DDDDDDDDDDDDD",    
    "DDDDDDD       DDDDDDDDDDDDD",
    "DDDDDDD       DDDDDDDDDDDDD",
]   
level_6_grid = [ 
    "DDLLLLLDDD                G",
    "DD     DDD                G",
    "DD     DDD                G",
    "DD     DDD                G",
    "DDDD   DDD    DDDDDDDDDDDDD",
    "DD     DDD               DD",
    "DD     DDD               DD",
    "DD     DDD               DD",
    "DD     DDD    ^^         DD",
    "DD     DDDDDDDDDDDDDD    DD",
    "DD     DDD^^^^^^^^^      DD",
    "DD     DDD               DD",
    "DD     DDD      C        DD",
    "DD     DDD     ^^       ^DD",
    "DD     DDD    ^DD^      ^DD",
    "DD     DDD              ^DD",
    "DD                      ^DD",
    "DD                      ^DD",
    "DD                      ^DD",
    "DD                      ^DD",
    "DD          ^^^^^^       DD",
    "DD         ^DDDDDD^   FF DD",
    "DD         ^DDDDDD^  DDDDDD",
    "DDDDDD   F  ^^^^^^   DDDDDD",    
    "DDDDDD   D           DDDDDD",
    "DDDDDD   D           DDDDDD",
]

level_7_grid = [
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DD^           DDDDD       G",
    "DD^   C       DDDDD       G",
    "DD^  ^^       ^^^^^       G",
    "DD^ ^DD^                  G",
    "DD^ ^DD^               DDDD",
    "DD^ ^DD^                 DD",
    "DD            ^^^^^      DD",
    "DD            DDDDDDDDDDDDD",
    "DD          F DDDDDDDDDDDDD",
    "DD     DDDDDDDDDDDDDDDDDDDD",
    "DD   DDD            DDDDDDD",
    "DD                    DDDDD",
    "DD                     DDDD",
    "DD                     DDDD",
    "DDDDDDDDDDDDDDD        DDDD",
    "B        ^^^^^D^^^^^   DDDD",
    "B             DDDDDD   DDDD",
    "B                      DDDD",
    "B                      DDDD",
    "B                   DDDDDDD",
    "L                        DD",
    "L                        DD",
    "DDDD   F    F    F       DD",    
    "DDDD   D    D    D       DD",
    "DDDD   D    D    D       DD",   
]

level_8_grid = [
    "G               DDDDDDDDDDD",
    "G                      DDDD",
    "G                    C DDDD",
    "G   ^^^              DDDDDD",
    "DD  DDD^             DDDDDD",
    "DD  ^^^              DDDDDD",
    "DD                     DDDD",
    "DD                     DDDD",
    "DD                     DDDD",
    "DD   F                 DDDD",
    "DDDDDDDDD              DDDD",
    "B                      DDDD",
    "B      ^^^^^           DDDD",
    "B     ^DDDDD        DDDDDDD",
    "B     ^DDDDDDD      ^^^^^^B",
    "B     ^DDDDDDD            B",
    "B        ^DDDDDDD         B",
    "B        ^D^^^^^^         B",
    "B        ^D               B",
    "L                         B",
    "L                         B",
    "L                    F    B",
    "L   DDD^             D    B",
    "DDDDDDD^    F        D    B",    
    "DDDDDDD^    D        D    B",
    "DDDDDDD^    D        D    B",   
]





level_9_grid = [
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDD^^^                 DDDD",
    "DD                       DD",
    "DD        C              DD",
    "DD^                      DD",
    "DDD  ^^^^^^^  ^^         DD",
    "G    DDDDDDDDDDD         DD",
    "G        ^^^^^^          DD",
    "G                        DD",
    "G                        DD",
    "DDDDDDDDDDDD      DD^    DD",
    "DDDDDDDDDDD        D^    DD",
    "DDDDDDDDDD^^^^^^^^^D     DD",
    "DDDDDDDDDDDDDDDDDDDD    ^DD",
    "B                       ^DD",
    "B                       ^DD",
    "B       ^^^^   ^^       ^DD",
    "B       DDDD   DD   FF   DD",
    "DDD  DDDDDDDDDDDDDDDDDDDDDD",
    "DDD              ^^^^^^^  L",
    "DDD                       L",
    "DDD    ^^   ^^            L",
    "DDD    DD   DD            L",
    "DDDDDDDDDDDDDDDDDD    DDDDD",    
    "DDDDDDDDDDDDDDDDDD    DDDDD",
    "DDDDDDDDDDDDDDDDDD    DDDDD",   
]


level_10_grid = [
    "B                                                                                                                                                        B",
    "B                                                                                                                                                        B",
    "B                                                                                                                                                        B",
    "B                                                                                                                                                        B",
    "B                                                                                                                                                        B",
    "B                                                                                                                                                        B",
    "B                                                                                                                                                        B",
    "B                                                                                                                                                        B",
    "B                      DDDDDD                                                                                                                            B",
    "B                         DDDDD                                                                                                                          B",
    "B                           DDDDD                                                                                                                        B",
    "B                            DDDDDD                                                                                                                      B",
    "B                             DDDDDD                                                                                                                     B",
    "B                             DDDDDDD                                                              C                                                     B",
    "B                                                                                                         ^^^                                            B",
    "B                                                                               ^^^^   ^^^     ^^^^^^     DDD^    ^^^                                    B",
    "B                                               ^                      ^^^^   DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD^   ^DDD                                    B",
    "B                                              ^D                      DDDDDDD^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^  ^DDD                                    B",
    "D                                              ^D                       ^^^^^^^                              ^D^  ^^^                                    B",
    "G                                              ^D   ^^                                                        D           ^^^                            L",
    "G                                              ^D   DD                                                        D           DDD                            L",
    "G                                                   DD           DDDDDDDDDD       DDDDD                          DD^^^    DDD                            L",
    "G                                       F           DD           DDDDDDDDDD       DDDDD   FFF   FF     F         DDDDD    DDD                            L",
    "DDDDD                                   DDDD        DD   F       DDDDDDDD         DDDDDDDDDDDDDDDDDDDDDDDDDD     DDDDDDDDDDDDDD            DDDDDD    DDDDD",    
    "DDDDD                                    DDD        DD   D       DDDDD            DDDDDDDDDDDDDDDDDDDDDDDDDD     DDDDDDDDDDDDDD            DDDDDD    DDDDD",
    "DDDDD                                     DD        DD   D       DDDDD            DDDDDDDDDDDDDDDDDDDDDDDDDD     DDDDDDDDDDDDDD            DDDDDD    DDDDD",   
]
 

all_level = [
    Level(1, level_1_grid, (96, 544), (2560, 578)),
    Level(2, level_2_grid, (96, 512), (736, 96)),
    Level(3, level_3_grid, (96, 544), (736, 96)),
    Level(4, level_4_grid, (96, 576), (64, 224)),
    Level(5, level_5_grid, (768, 608), (96, 640)),
    Level(6, level_6_grid, (64, 64), (736, 64)),
    Level(7, level_7_grid, (64, 576), (736, 64)),
    Level(8, level_8_grid, (64, 576), (64, 64)),
    Level(9, level_9_grid, (768, 608), (96, 192)),
    # Level(10, level_10_grid, (4800, 578), (64, 64)),
    Level(10, level_10_grid, (100, 578), (64, 64)),

]