from level import Level

WIDTH, HEIGHT = 800, 800
TILE_SIZE = 32

level_1_grid = [
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                                                    G",
    "B                                                  DDDDDDD                           G",
    "B                                                  DDDDDD                            G",
    "B                                                  DDDDDD                            G",
    "B                                                  DDDDDD                            G",
    "B                                                  DDDDD                             G",
    "B                                                  DDDDD                             G",
    "B                                                  DDDDD            DDDDD            G",
    "B                                                DDDDD                               G",
    "B                         DDDD                   DDDD                                G",
    "B                 DDDDD                          DDDD C                              G",
    "B                                 DDDDD          DDDD              DDD               G",
    "B                                                DDDD              DDD               G",
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",    
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",            
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",            
    "DDDDDD    DDDDDDDDDD                       DDDDDDDDDDDDD       DDDDDDDDDDD     DDDDDDD",             
]
level_2_grid = [ 
    "B                         G",
    "B                         G",
    "B                         G",
    "B C                       G",
    "B                         G",
    "B                    DDDDDD",
    "B                        DD",
    "B    DDD                 DD",
    "B    DDD                 DD",
    "D^^^^DDD                 DD",
    "DDDDDDD                  DD",
    "DDDDD            DD      DD",
    "DDDD             DD      DD",
    "DD                       DD",
    "DD                       DD",
    "L                      DDDD",
    "L                      DDDD",
    "L                      DDDD",
    "L                    DDDDDD",
    "L                        DD",
    "L                        DD",
    "DDDDDD    DDDDD          DD",
    "DDDDDD    DDDDD    ^^^^^^DD",
    "DDDDDD^^^^DDDDD^^^^DDDDDDDD",    
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
]
level_3_grid = [ 
    "B                   DGGGGDD",
    "B                   D    DD",
    "B                   D    DD",
    "B                   D    DD",
    "B                   D    DD",
    "B                   D    DD",
    "B                   D    DD",
    "B      DDDDDD            DD",
    "B      ^^^^^^            DD",
    "B                        DD",
    "B         C   DD      DDDDD",
    "DDD                      DD",
    "B      ^^^^^^^^^^        DD",
    "B      DDDDDDDDDD        DD",
    "B    DDDDDDDDDDDD^^^     DD",
    "B      DDDDDDDDDDDDD^^^^^DD",
    "B      DDDDDDDDDDDDDDDDDDDD",
    "B      DDDDDDDDDDDDDDDDDDDD",
    "DDD    DDDDDDDDDDDDDDDDDDDD",
    "L      DDDDDDDDDDDDDDDDDDDD",
    "L      DDDDDDDDDDDDDDDDDDDD",
    "L      DDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",    
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
]
level_4_grid = [ 
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDD                   DD",
    "DDDD                 C   DD",
    "DD                       DD",
    "G                    ^   DD",
    "G                   ^D^  DD",
    "G                   ^D^  DD",
    "G                   ^D^  DD",
    "DDDDDD               ^   DD",
    "B                        DD",
    "B                        DD",
    "B                 DDDDDDDDD",
    "B                       DDD",
    "B                        DD",
    "DDDDDDDD                 DD",
    "DDDD                     DD",
    "DDD               DD     DD",
    "DD                DDDDD  DD",
    "L                        DD",
    "L                        DD",
    "L                      DDDD",
    "L                    DDDDDD",
    "DDDDDD            DDDDDDDDD",
    "DDDDDD^^^^^^^^^^^^DDDDDDDDD",    
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDD",
]

level_5_grid = [ 
    "DDDDDD                  ^DD",
    "DDDDDD                  ^DD",
    "DDDD                    ^DD",
    "DD                      ^DD",
    "D                        DD",
    "D            ^^^^        DD",
    "DDDDDD^   ^DDDDDDDDDD    DD",
    "DDDDDD^   ^DDDDDDDDDD^   DD",
    "DDDDDD^   ^DDDDDDDDDD^   DD",
    "DDDDDD^   ^DDDDDDDDDD^   DD",
    "DDDDDD^   ^DDDDDDDDDD^   DD",
    "DD        ^DDDDDDDDDD    DD",
    "B  C           DDDDDD    DD",
    "B    ^         DDDDDD   ^DD",
    "DD   D^        DDDDDD   ^DD",
    "D^   D^^^^^    DDDDDD    DD",
    "D^    DDDDD    DDDDDD    DD",
    "D^      ^^^       DDD^   DD",
    "D^^^               DD^   DD",
    "DDDDDDDDDDDDDDD    DD     L",
    "G                  DD     L",
    "G                  DD     L",
    "G                 DDDDDDDDD",
    "DDDDDDD       DDDDDDDDDDDDD",    
    "DDDDDDD       DDDDDDDDDDDDD",
    "DDDDDDD       DDDDDDDDDDDDD",
]    

all_level = [
    Level(1, level_1_grid, (96, 544), (2560, 578)),
    Level(2, level_2_grid, (96, 512), (736, 96)),
    Level(3, level_3_grid, (96, 544), (736, 96)),
    Level(4, level_4_grid, (96, 576), (64, 224)),
    Level(5, level_5_grid, (768, 608), (96, 512)),
]